In [1]:
print("hello")


hello


In [4]:
j=10


In [10]:
import numpy as np

In [18]:
import numpy as np
arr = np.array([1,3,4,5])
arr

array([1, 3, 4, 5])

In [2]:
import numpy as np
arr = np.array([1,3,4,5])
arr
arr.shape

(4,)

In [3]:
import numpy as np
arr = np.array([1,3,4,5])
arr
arr.dtype

dtype('int64')

In [5]:
import numpy as np
myarr = np.array([[1,2,3], [2,3,4],[5,6,7]])
myarr

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

1. Conversion from Python structures
   You can create a NumPy array from existing Python data structures like lists or tuples.

In [6]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
import numpy as np
a = np.array(("apple","orange","mango"))
print(a)

['apple' 'orange' 'mango']


2. Intrinsic NumPy array creation objects ⭐

This means NumPy itself provides functions to directly create arrays, without first creating a list

In [9]:
np.zeros(18)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [11]:
np.arange(1,5)

array([1, 2, 3, 4])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.full(2,6)

array([6, 6])

In [15]:
np.full(1,5)

array([5])

In [16]:
np.random.rand(4)

array([0.20379892, 0.56096579, 0.48361527, 0.02704172])

In [17]:
np.linspace(1,9,5)

array([1., 3., 5., 7., 9.])

In [4]:
import numpy as np
ide = np.identity(12)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [6]:
ide.shape

(12, 12)

In [7]:
np.shape

<function shape at 0x000002114A45E370>

In [10]:
import numpy as np
arr= np.arange(99)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [12]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [15]:
import numpy as np
arr = np.array([[1,2,3],
               [2,3,4],
               [4,56,6]])
print(arr)
arr.sum(axis=0)     

[[ 1  2  3]
 [ 2  3  4]
 [ 4 56  6]]


array([ 7, 61, 13])

In [16]:
arr.sum(axis=1)

array([ 6,  9, 66])

In [17]:
arr.T

array([[ 1,  2,  4],
       [ 2,  3, 56],
       [ 3,  4,  6]])

In [18]:
arr.ndim

2

In [19]:
for i in arr.flat:
    print(arr)

[[ 1  2  3]
 [ 2  3  4]
 [ 4 56  6]]
[[ 1  2  3]
 [ 2  3  4]
 [ 4 56  6]]
[[ 1  2  3]
 [ 2  3  4]
 [ 4 56  6]]
[[ 1  2  3]
 [ 2  3  4]
 [ 4 56  6]]
[[ 1  2  3]
 [ 2  3  4]
 [ 4 56  6]]
[[ 1  2  3]
 [ 2  3  4]
 [ 4 56  6]]
[[ 1  2  3]
 [ 2  3  4]
 [ 4 56  6]]
[[ 1  2  3]
 [ 2  3  4]
 [ 4 56  6]]
[[ 1  2  3]
 [ 2  3  4]
 [ 4 56  6]]


In [20]:
for i in arr.flat:
    print(i)

1
2
3
2
3
4
4
56
6


In [21]:
arr.nbytes

72

In [22]:
one = np.array([1,2,33,5,6])
one.argmax()

np.int64(2)

In [23]:
one.argmin()

np.int64(0)

In [24]:
one.argmax()


np.int64(2)

In [25]:
one.argsort()

array([0, 1, 3, 4, 2])

In [37]:
arr1 = np.array([[100,2,3],
                 [56,33,42],
                 [9,90,1]])
arr1.argmin()

np.int64(8)

In [38]:
arr1.argmax()

np.int64(0)

In [39]:
arr1.argsort()

array([[1, 2, 0],
       [1, 2, 0],
       [2, 0, 1]])

In [40]:
arr1.argmax(axis = 0)

array([0, 2, 1])

In [41]:
arr1.argsort(axis =0)

array([[2, 0, 2],
       [1, 1, 0],
       [0, 2, 1]])

In [42]:
arr = np.array([3,1,2])
arr.argsort()

array([1, 2, 0])

In [43]:
arr = np.array([[1,9,5],
                [3,22,2]])
arr.argsort()

array([[0, 2, 1],
       [2, 0, 1]])

In [44]:
arr = np.array([[0,1,2],
                [0,1,2],
                [2,1,0]])
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [45]:
arr.ravel()

array([0, 1, 2, 0, 1, 2, 2, 1, 0])

In [2]:
import numpy as np
ar1 = np.array([[1,1,1],
                [2,2,5],
                [4,7,5]])
ar1
ar2 = np.array([[2,4,5],
                [6,7,8],
                [3,9,1]])
ar2
ar1 + ar2

array([[ 3,  5,  6],
       [ 8,  9, 13],
       [ 7, 16,  6]])

In [3]:
[1,2] + [4,5]

[1, 2, 4, 5]

In [4]:
ar1 * ar2

array([[ 2,  4,  5],
       [12, 14, 40],
       [12, 63,  5]])

In [5]:
np.sqrt(ar1)

array([[1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 2.23606798],
       [2.        , 2.64575131, 2.23606798]])

In [6]:
ar1.min()

np.int64(1)

In [7]:
ar1.max()

np.int64(7)

In [8]:
np.where(ar1>5)

(array([2]), array([1]))

In [9]:
np.count_nonzero(ar1)

np.int64(9)

In [11]:
np.nonzero(ar1)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [13]:
ar = np.array([1,2,5,0,9])
np.nonzero(ar)

(array([0, 1, 2, 4]),)

In [ ]:
np.where(ar>5)